### ISSUE TITLE
Generate frozen binary for windows.

### ISSUE THREAD

**Issue by vasole** [vasole/pymca_launcher#3]
Try to freeze the launcher script in a cleaner way than PyMca5 does it in order to simplify future freezing of applications based on silx.

**Comment by PiRK** [comment]
After a lot of testing, I found that the simplest setup script that will generate a working binary version of pymca_launcher is : https://github.com/PiRK/pymca_launcher/blob/f989c9224e13418bdf1f754eb78cd9802d02f843/cx_setup.py

It assumes that PyMca and fisx are already installed.

Now I need to find a blank Windows computer (without qt, matplotlib, python …)  to test the generated binary.

**Comment by vasole** [comment]
Working with current master under windows with python 3.6 and 3.7
